### ISSUE TITLE
(Native) English proofreading

### ISSUE THREAD

**Issue by willdurand** [TailorDev/manifesto#12]
Hi!

As non-native English speakers/writers, we are looking for people willing to proofread this **open manifesto**.

Thank you for your help ❤️

**Comment by RaoOfPhysics** [comment]
I can take a stab at this!

**Comment by willdurand** [comment]
@RaoOfPhysics that would be awesome 😍

**Comment by RaoOfPhysics** [comment]
Forked your repo and will poke around when I have time. Will definitely submit a PR with suggested changes. I'll try and make commits when I can and you can review them. At the end you might consider squashing them if needed. :)

**Comment by moingshaikh** [comment]
I would be glad to help.

**Comment by PixelAtLarge** [comment]
I can help with this 🙋🏻

**Comment by willdurand** [comment]
Hi @moinshaikh and @PixelAtLarge! Thanks for your interest in reviewing this manifesto, especially because our small company believes in it a lot! And it is great to have it proofread by all of you. @RaoOfPhysics already raided his hand to review it, so I suggest you all work together. Maybe you could review @RaoOfPhysics's PR?

**Comment by RaoOfPhysics** [comment]
@willdurand: Actually, since @PixelAtLarge has been much faster than I have in providing feedback, maybe I can comment on her edits in the PR? Alternatively, maybe you can merge that PR and I can give it a second look once it's merged. Let me know what you prefer. :) I'm open to any option!

**Comment by willdurand** [comment]
> @willdurand: Actually, since @PixelAtLarge has been much faster than I have in providing feedback, maybe I can comment on her edits in the PR? Alternatively, maybe you can merge that PR and I can give it a second look once it's merged. Let me know what you prefer. :) I'm open to any option!

Sounds like a great plan!

@RaoOfPhysics I let you comment on @PixelAtLarge's PR then, and if she can do the changes, we will deal with her PR only. Ok?

**Comment by Bkorotko03** [comment]
Will do

**Comment by willdurand** [comment]
> Will do

@Bkorotko03 Will do.. what? This issue is already assigned to many people. Please find another issue here: https://github.com/search?q=org%3ATailorDev+is%3Aissue+is%3Aopen+label%3Ahacktoberfest.

**Comment by RaoOfPhysics** [comment]
@willdurand: Have made some comments on @PixelAtLarge's PR: https://github.com/TailorDev/manifesto/pull/16#pullrequestreview-2145655

**Comment by PixelAtLarge** [comment]
@RaoOfPhysics Thanks for taking the time to review my PR! 

@willdurand How would you feel about merging my PR first (if you are okay with the changes), and then letting @RaoOfPhysics open up a second PR to incorporate the additional changes he suggested? I just want to make sure he also gets credit towards hacktoberfest! 🎃

**Comment by willdurand** [comment]
@PixelAtLarge I am going to review @RaoOfPhysics' review, and likely require a few changes. I will leave @RaoOfPhysics additional changes though, so that he will be able to open a PR too. Ok?

**Comment by krisnotchris** [comment]
I was an English major at one point :P i'll see what I can come up with!

**Comment by willdurand** [comment]
@PixelAtLarge is there anything I can do to help you with your PR? Thanks!

**Comment by PixelAtLarge** [comment]
@willdurand Should be all set - thanks for checking. I can incorporate any final changes based on the comments today after work 🙂

**Comment by PixelAtLarge** [comment]
@willdurand All comments in #16 have been taken care of

**Comment by willdurand** [comment]
@PixelAtLarge perfect! thank you so much!!!

@RaoOfPhysics you can add/slightly update some parts if you wish  :-)

**Comment by RaoOfPhysics** [comment]
@willdurand: A bit occupied today, but you will have the changes tomorrow. :)

**Comment by willdurand** [comment]
> @willdurand: A bit occupied today, but you will have the changes tomorrow. :)

Oh don't worry, you have until the end of this month (at least) ;-)

**Comment by tanvibhakta** [comment]
Ooh, it looks like there are enough people already! Anything I could do to help?

**Comment by willdurand** [comment]
Hey @tanvibhakta, I am not sure there is some more work left here unfortunately.. Thank you for your interest!

**Comment by willdurand** [comment]
Thanks everyone!
